namespace: sofia-mosquera-dev
name: microservico-1

metadata:
  labels:
    app: mi-app-1

replicaCount: 1

container:
  # Full image name without tag (e.g. 'adonispaz9506/hola-mundo-clase567')
  image: "sofiamosquera/smcursoopenshift"
  tag: build-{{ tag }}
  port: 3000
  resources:
    requests:
      cpu: "200m"
      memory: "300Mi"
    limits:
      cpu: "4000m"
      memory: "500Mi"

service:
  type: ClusterIP
  port: 4000

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configmap:
  database: "192.168.1.1"

secret:
  # plain text password; template will base64-encode when placing into `data:`
  password: "hola"
