name: CI-DockerBuild

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    # El tipo de máquina virtual donde se ejecutará el job
    runs-on: ubuntu-latest

    # Los pasos que componen el job
    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_TOKEN  }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME  }}/smcursoopenshift
          tags: |
            type=raw,value=build-${{ github.run_number }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OC CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
          sudo mv oc /usr/local/bin/
          oc version
    
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
          
      - name: Log in Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm1.0a51.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OC_TOKEN }}
      
      - name: Set project
        run: oc project sofia-mosquera-dev

      - name: Update Deployment tag
        run: |
          echo "Reemplazando {{ tag }} con ${{ github.run_number }}"
          sed -i "s|{{ tag }}|${{ github.run_number }}|g" values.yaml
          cat values.yaml

      - name: Deploy files
        run: |
          helm show chart oci://registry-1.docker.io/sofiamosquera/mi-chart --version 3
          helm upgrade --install microservicio-1 oci://registry-1.docker.io/sofiamosquera/mi-chart --version 3 --values values.yaml
